
USE [Pronto]
GO
CREATE TABLE [TABVEN11REP] (
  [TABVEN11REPIdUni] DECIMAL(10)    NOT NULL    IDENTITY ( 1 , 1 ),
  [UEstCod]          VARCHAR(128)    NOT NULL,
  [TavNum]           SMALLINT    NOT NULL,
     PRIMARY KEY ( [TABVEN11REPIdUni] ))
CREATE NONCLUSTERED INDEX [ITABVEN11REP1] ON [TABVEN11REP] (
      [TavNum],
      [TavVigDtaIni]
CREATE NONCLUSTERED INDEX [ITABVEN11REP2] ON [TABVEN11REP] (
      [UEstCod])
ALTER TABLE [TABVEN11REP]
 ADD CONSTRAINT [ITABVEN11REP2] FOREIGN KEY ( [UEstCod] ) REFERENCES [USUEST]([UEstCod])
ALTER TABLE [TABVEN11REP]
 --ADD CONSTRAINT [ITABVEN11REP1] FOREIGN KEY ( [TavNum] ) REFERENCES [TABVEN05]([TavNum],[TavVigDtaIni],[TavAdqCod],[TavBanCod],[TavDetSeq])
  ADD CONSTRAINT [ITABVEN11REP1] FOREIGN KEY ( [TavNum] ) FOREIGN KEY ( [TavNum] ) REFERENCES [TABVEN]([TavNum])	

GO

USE [Banese]
GO
CREATE TABLE [TABVEN11REP] (
  [TABVEN11REPIdUni] DECIMAL(10)    NOT NULL    IDENTITY ( 1 , 1 ),
  [UEstCod]          VARCHAR(128)    NOT NULL,
  [TavNum]           SMALLINT    NOT NULL,
     PRIMARY KEY ( [TABVEN11REPIdUni] ))
CREATE NONCLUSTERED INDEX [ITABVEN11REP1] ON [TABVEN11REP] (
      [TavNum],
      [TavVigDtaIni]
CREATE NONCLUSTERED INDEX [ITABVEN11REP2] ON [TABVEN11REP] (
      [UEstCod])
ALTER TABLE [TABVEN11REP]
 ADD CONSTRAINT [ITABVEN11REP2] FOREIGN KEY ( [UEstCod] ) REFERENCES [USUEST]([UEstCod])
ALTER TABLE [TABVEN11REP]
 --ADD CONSTRAINT [ITABVEN11REP1] FOREIGN KEY ( [TavNum] ) REFERENCES [TABVEN05]([TavNum],[TavVigDtaIni],[TavAdqCod],[TavBanCod],[TavDetSeq])
  ADD CONSTRAINT [ITABVEN11REP1] FOREIGN KEY ( [TavNum] ) FOREIGN KEY ( [TavNum] ) REFERENCES [TABVEN]([TavNum])	

GO

USE [BemFacil]
GO
CREATE TABLE [TABVEN11REP] (
  [TABVEN11REPIdUni] DECIMAL(10)    NOT NULL    IDENTITY ( 1 , 1 ),
  [UEstCod]          VARCHAR(128)    NOT NULL,
  [TavNum]           SMALLINT    NOT NULL,
     PRIMARY KEY ( [TABVEN11REPIdUni] ))
CREATE NONCLUSTERED INDEX [ITABVEN11REP1] ON [TABVEN11REP] (
      [TavNum],
      [TavVigDtaIni]
CREATE NONCLUSTERED INDEX [ITABVEN11REP2] ON [TABVEN11REP] (
      [UEstCod])
ALTER TABLE [TABVEN11REP]
 ADD CONSTRAINT [ITABVEN11REP2] FOREIGN KEY ( [UEstCod] ) REFERENCES [USUEST]([UEstCod])
ALTER TABLE [TABVEN11REP]
 --ADD CONSTRAINT [ITABVEN11REP1] FOREIGN KEY ( [TavNum] ) REFERENCES [TABVEN05]([TavNum],[TavVigDtaIni],[TavAdqCod],[TavBanCod],[TavDetSeq])
  ADD CONSTRAINT [ITABVEN11REP1] FOREIGN KEY ( [TavNum] ) FOREIGN KEY ( [TavNum] ) REFERENCES [TABVEN]([TavNum])	

GO

USE [Credinov]
GO
CREATE TABLE [TABVEN11REP] (
  [TABVEN11REPIdUni] DECIMAL(10)    NOT NULL    IDENTITY ( 1 , 1 ),
  [UEstCod]          VARCHAR(128)    NOT NULL,
  [TavNum]           SMALLINT    NOT NULL,
     PRIMARY KEY ( [TABVEN11REPIdUni] ))
CREATE NONCLUSTERED INDEX [ITABVEN11REP1] ON [TABVEN11REP] (
      [TavNum],
      [TavVigDtaIni]
CREATE NONCLUSTERED INDEX [ITABVEN11REP2] ON [TABVEN11REP] (
      [UEstCod])
ALTER TABLE [TABVEN11REP]
 ADD CONSTRAINT [ITABVEN11REP2] FOREIGN KEY ( [UEstCod] ) REFERENCES [USUEST]([UEstCod])
ALTER TABLE [TABVEN11REP]
 --ADD CONSTRAINT [ITABVEN11REP1] FOREIGN KEY ( [TavNum] ) REFERENCES [TABVEN05]([TavNum],[TavVigDtaIni],[TavAdqCod],[TavBanCod],[TavDetSeq])
  ADD CONSTRAINT [ITABVEN11REP1] FOREIGN KEY ( [TavNum] ) FOREIGN KEY ( [TavNum] ) REFERENCES [TABVEN]([TavNum])	

GO

USE [CredPag]
GO
CREATE TABLE [TABVEN11REP] (
  [TABVEN11REPIdUni] DECIMAL(10)    NOT NULL    IDENTITY ( 1 , 1 ),
  [UEstCod]          VARCHAR(128)    NOT NULL,
  [TavNum]           SMALLINT    NOT NULL,
     PRIMARY KEY ( [TABVEN11REPIdUni] ))
CREATE NONCLUSTERED INDEX [ITABVEN11REP1] ON [TABVEN11REP] (
      [TavNum],
      [TavVigDtaIni]
CREATE NONCLUSTERED INDEX [ITABVEN11REP2] ON [TABVEN11REP] (
      [UEstCod])
ALTER TABLE [TABVEN11REP]
 ADD CONSTRAINT [ITABVEN11REP2] FOREIGN KEY ( [UEstCod] ) REFERENCES [USUEST]([UEstCod])
ALTER TABLE [TABVEN11REP]
 --ADD CONSTRAINT [ITABVEN11REP1] FOREIGN KEY ( [TavNum] ) REFERENCES [TABVEN05]([TavNum],[TavVigDtaIni],[TavAdqCod],[TavBanCod],[TavDetSeq])
  ADD CONSTRAINT [ITABVEN11REP1] FOREIGN KEY ( [TavNum] ) FOREIGN KEY ( [TavNum] ) REFERENCES [TABVEN]([TavNum])	

GO

USE [SmartPagamentos]
GO
CREATE TABLE [TABVEN11REP] (
  [TABVEN11REPIdUni] DECIMAL(10)    NOT NULL    IDENTITY ( 1 , 1 ),
  [UEstCod]          VARCHAR(128)    NOT NULL,
  [TavNum]           SMALLINT    NOT NULL,
     PRIMARY KEY ( [TABVEN11REPIdUni] ))
CREATE NONCLUSTERED INDEX [ITABVEN11REP1] ON [TABVEN11REP] (
      [TavNum],
      [TavVigDtaIni]
CREATE NONCLUSTERED INDEX [ITABVEN11REP2] ON [TABVEN11REP] (
      [UEstCod])
ALTER TABLE [TABVEN11REP]
 ADD CONSTRAINT [ITABVEN11REP2] FOREIGN KEY ( [UEstCod] ) REFERENCES [USUEST]([UEstCod])
ALTER TABLE [TABVEN11REP]
 --ADD CONSTRAINT [ITABVEN11REP1] FOREIGN KEY ( [TavNum] ) REFERENCES [TABVEN05]([TavNum],[TavVigDtaIni],[TavAdqCod],[TavBanCod],[TavDetSeq])
  ADD CONSTRAINT [ITABVEN11REP1] FOREIGN KEY ( [TavNum] ) FOREIGN KEY ( [TavNum] ) REFERENCES [TABVEN]([TavNum])	

GO


  
  
  