/* TAREFA #14433 - JOSÉ */

--Rodar em todos os clientes
CREATE NONCLUSTERED INDEX [UPOS] ON [POS] (
      [PosEstCod],
      [PosStsPos])

/* TAREFA #17023 - JOSÉ */

--Clientes que irão usar o script
USE Banese
USE BemFacil
USE Credinov
USE CredPag
USE Pronto
USE SmartPagamentos

ALTER TABLE [USUEST]
ADD [UEstStatus] BIT    NULL

UPDATE USUEST
SET UEstStatus = 1

/* TAREFA #17934 - JOÃO */

USE [Pronto]
GO
CREATE TABLE [TABVEN11REP] (
  [TABVEN11REPIdUni] DECIMAL(10)    NOT NULL    IDENTITY ( 1 , 1 ),
  [UEstCod]          VARCHAR(128)    NOT NULL,
  [TavNum]           SMALLINT    NOT NULL,
     PRIMARY KEY ( [TABVEN11REPIdUni] ))
CREATE NONCLUSTERED INDEX [ITABVEN11REP1] ON [TABVEN11REP] (
      [TavNum],
      [TavVigDtaIni]
CREATE NONCLUSTERED INDEX [ITABVEN11REP2] ON [TABVEN11REP] (
      [UEstCod])
ALTER TABLE [TABVEN11REP]
 ADD CONSTRAINT [ITABVEN11REP2] FOREIGN KEY ( [UEstCod] ) REFERENCES [USUEST]([UEstCod])
ALTER TABLE [TABVEN11REP]
 --ADD CONSTRAINT [ITABVEN11REP1] FOREIGN KEY ( [TavNum] ) REFERENCES [TABVEN05]([TavNum],[TavVigDtaIni],[TavAdqCod],[TavBanCod],[TavDetSeq])
  ADD CONSTRAINT [ITABVEN11REP1] FOREIGN KEY ( [TavNum] ) FOREIGN KEY ( [TavNum] ) REFERENCES [TABVEN]([TavNum])	

GO

USE [Banese]
GO
CREATE TABLE [TABVEN11REP] (
  [TABVEN11REPIdUni] DECIMAL(10)    NOT NULL    IDENTITY ( 1 , 1 ),
  [UEstCod]          VARCHAR(128)    NOT NULL,
  [TavNum]           SMALLINT    NOT NULL,
     PRIMARY KEY ( [TABVEN11REPIdUni] ))
CREATE NONCLUSTERED INDEX [ITABVEN11REP1] ON [TABVEN11REP] (
      [TavNum],
      [TavVigDtaIni]
CREATE NONCLUSTERED INDEX [ITABVEN11REP2] ON [TABVEN11REP] (
      [UEstCod])
ALTER TABLE [TABVEN11REP]
 ADD CONSTRAINT [ITABVEN11REP2] FOREIGN KEY ( [UEstCod] ) REFERENCES [USUEST]([UEstCod])
ALTER TABLE [TABVEN11REP]
 --ADD CONSTRAINT [ITABVEN11REP1] FOREIGN KEY ( [TavNum] ) REFERENCES [TABVEN05]([TavNum],[TavVigDtaIni],[TavAdqCod],[TavBanCod],[TavDetSeq])
  ADD CONSTRAINT [ITABVEN11REP1] FOREIGN KEY ( [TavNum] ) FOREIGN KEY ( [TavNum] ) REFERENCES [TABVEN]([TavNum])	

GO

USE [BemFacil]
GO
CREATE TABLE [TABVEN11REP] (
  [TABVEN11REPIdUni] DECIMAL(10)    NOT NULL    IDENTITY ( 1 , 1 ),
  [UEstCod]          VARCHAR(128)    NOT NULL,
  [TavNum]           SMALLINT    NOT NULL,
     PRIMARY KEY ( [TABVEN11REPIdUni] ))
CREATE NONCLUSTERED INDEX [ITABVEN11REP1] ON [TABVEN11REP] (
      [TavNum],
      [TavVigDtaIni]
CREATE NONCLUSTERED INDEX [ITABVEN11REP2] ON [TABVEN11REP] (
      [UEstCod])
ALTER TABLE [TABVEN11REP]
 ADD CONSTRAINT [ITABVEN11REP2] FOREIGN KEY ( [UEstCod] ) REFERENCES [USUEST]([UEstCod])
ALTER TABLE [TABVEN11REP]
 --ADD CONSTRAINT [ITABVEN11REP1] FOREIGN KEY ( [TavNum] ) REFERENCES [TABVEN05]([TavNum],[TavVigDtaIni],[TavAdqCod],[TavBanCod],[TavDetSeq])
  ADD CONSTRAINT [ITABVEN11REP1] FOREIGN KEY ( [TavNum] ) FOREIGN KEY ( [TavNum] ) REFERENCES [TABVEN]([TavNum])	

GO

USE [Credinov]
GO
CREATE TABLE [TABVEN11REP] (
  [TABVEN11REPIdUni] DECIMAL(10)    NOT NULL    IDENTITY ( 1 , 1 ),
  [UEstCod]          VARCHAR(128)    NOT NULL,
  [TavNum]           SMALLINT    NOT NULL,
     PRIMARY KEY ( [TABVEN11REPIdUni] ))
CREATE NONCLUSTERED INDEX [ITABVEN11REP1] ON [TABVEN11REP] (
      [TavNum],
      [TavVigDtaIni]
CREATE NONCLUSTERED INDEX [ITABVEN11REP2] ON [TABVEN11REP] (
      [UEstCod])
ALTER TABLE [TABVEN11REP]
 ADD CONSTRAINT [ITABVEN11REP2] FOREIGN KEY ( [UEstCod] ) REFERENCES [USUEST]([UEstCod])
ALTER TABLE [TABVEN11REP]
 --ADD CONSTRAINT [ITABVEN11REP1] FOREIGN KEY ( [TavNum] ) REFERENCES [TABVEN05]([TavNum],[TavVigDtaIni],[TavAdqCod],[TavBanCod],[TavDetSeq])
  ADD CONSTRAINT [ITABVEN11REP1] FOREIGN KEY ( [TavNum] ) FOREIGN KEY ( [TavNum] ) REFERENCES [TABVEN]([TavNum])	

GO

USE [CredPag]
GO
CREATE TABLE [TABVEN11REP] (
  [TABVEN11REPIdUni] DECIMAL(10)    NOT NULL    IDENTITY ( 1 , 1 ),
  [UEstCod]          VARCHAR(128)    NOT NULL,
  [TavNum]           SMALLINT    NOT NULL,
     PRIMARY KEY ( [TABVEN11REPIdUni] ))
CREATE NONCLUSTERED INDEX [ITABVEN11REP1] ON [TABVEN11REP] (
      [TavNum],
      [TavVigDtaIni]
CREATE NONCLUSTERED INDEX [ITABVEN11REP2] ON [TABVEN11REP] (
      [UEstCod])
ALTER TABLE [TABVEN11REP]
 ADD CONSTRAINT [ITABVEN11REP2] FOREIGN KEY ( [UEstCod] ) REFERENCES [USUEST]([UEstCod])
ALTER TABLE [TABVEN11REP]
 --ADD CONSTRAINT [ITABVEN11REP1] FOREIGN KEY ( [TavNum] ) REFERENCES [TABVEN05]([TavNum],[TavVigDtaIni],[TavAdqCod],[TavBanCod],[TavDetSeq])
  ADD CONSTRAINT [ITABVEN11REP1] FOREIGN KEY ( [TavNum] ) FOREIGN KEY ( [TavNum] ) REFERENCES [TABVEN]([TavNum])	

GO

USE [SmartPagamentos]
GO
CREATE TABLE [TABVEN11REP] (
  [TABVEN11REPIdUni] DECIMAL(10)    NOT NULL    IDENTITY ( 1 , 1 ),
  [UEstCod]          VARCHAR(128)    NOT NULL,
  [TavNum]           SMALLINT    NOT NULL,
     PRIMARY KEY ( [TABVEN11REPIdUni] ))
CREATE NONCLUSTERED INDEX [ITABVEN11REP1] ON [TABVEN11REP] (
      [TavNum],
      [TavVigDtaIni]
CREATE NONCLUSTERED INDEX [ITABVEN11REP2] ON [TABVEN11REP] (
      [UEstCod])
ALTER TABLE [TABVEN11REP]
 ADD CONSTRAINT [ITABVEN11REP2] FOREIGN KEY ( [UEstCod] ) REFERENCES [USUEST]([UEstCod])
ALTER TABLE [TABVEN11REP]
 --ADD CONSTRAINT [ITABVEN11REP1] FOREIGN KEY ( [TavNum] ) REFERENCES [TABVEN05]([TavNum],[TavVigDtaIni],[TavAdqCod],[TavBanCod],[TavDetSeq])
  ADD CONSTRAINT [ITABVEN11REP1] FOREIGN KEY ( [TavNum] ) FOREIGN KEY ( [TavNum] ) REFERENCES [TABVEN]([TavNum])	

GO

/* TAREFA #17836 - JOÃO */

USE [Pronto]
GO
ALTER TABLE [ADQ0008] 
ADD [AdqMccGrupoSegmento] CHAR(150)    NOT NULL CONSTRAINT AdqMccGrupoSegmentoADQ0008_DEFAULT DEFAULT ''
GO

USE [Banese]
GO
ALTER TABLE [ADQ0008] 
ADD [AdqMccGrupoSegmento] CHAR(150)    NOT NULL CONSTRAINT AdqMccGrupoSegmentoADQ0008_DEFAULT DEFAULT ''
GO

USE [BemFacil]
GO
ALTER TABLE [ADQ0008] 
ADD [AdqMccGrupoSegmento] CHAR(150)    NOT NULL CONSTRAINT AdqMccGrupoSegmentoADQ0008_DEFAULT DEFAULT ''
GO

USE [Credinov]
GO
ALTER TABLE [ADQ0008] 
ADD [AdqMccGrupoSegmento] CHAR(150)    NOT NULL CONSTRAINT AdqMccGrupoSegmentoADQ0008_DEFAULT DEFAULT ''
GO

USE [CredPag]
GO
ALTER TABLE [ADQ0008] 
ADD [AdqMccGrupoSegmento] CHAR(150)    NOT NULL CONSTRAINT AdqMccGrupoSegmentoADQ0008_DEFAULT DEFAULT ''
GO

USE [SmartPagamentos]
GO
ALTER TABLE [ADQ0008] 
ADD [AdqMccGrupoSegmento] CHAR(150)    NOT NULL CONSTRAINT AdqMccGrupoSegmentoADQ0008_DEFAULT DEFAULT ''
GO

/* TAREFA #18134 - JOSÉ */

USE Banese
USE BemFacil
USE Credinov
USE Credpag
USE Pronto
USE SmartPagamentos

ALTER TABLE [CONFIGURACAO] 
ADD [ConfigAplicacao] VARCHAR(40)    NULL,
	[ConfigImgLogoIcone_GXI] VARCHAR(2048)    NULL, 
    [ConfigImgLogoIcone] VARBINARY(MAX)    NULL,
	[ConfigImgAvatar_GXI] VARCHAR(2048)    NULL, 
    [ConfigImgAvatar] VARBINARY(MAX)    NULL

USE Banese

UPDATE Configuracao
SET ConfigAplicacao = 'baneseev15'

USE BemFacil

UPDATE Configuracao
SET ConfigAplicacao = 'bemfacilev15'
WHERE ConfigId = 1

UPDATE Configuracao
SET ConfigAplicacao = 'prosperaev15'
WHERE ConfigId = 2

USE Credinov

UPDATE Configuracao
SET ConfigAplicacao = 'credinovev15'

USE Credpag

UPDATE Configuracao
SET ConfigAplicacao = 'credpagev15'

USE Pronto

UPDATE Configuracao
SET ConfigAplicacao = 'prontoev15'

USE SmartPagamentos

UPDATE Configuracao
SET ConfigAplicacao = 'smartpagamentosev15'