--INDEX MOVTRN01
CREATE NONCLUSTERED INDEX [UMOVTRN016] ON [MovTrn01] (
      [MovTrnDta],
      [MovTrnParQtd],
      [MovTrnNsu],
      [MovTrnVlr])

-- INDEX LOGCON
DROP INDEX [ILOGCON2] ON [LOGCON]

CREATE NONCLUSTERED INDEX [ULOGCON] ON [LOGCON] (
      [LocNumLog] DESC,
      [LocNomExtArq])

-- COLUNA NOVA MOVTRN01
ALTER TABLE [MovTrn01]
ADD [MovtrnAnt] VARCHAR(1)     NOT NULL CONSTRAINT MovtrnAntMovTrn01_DEFAULT DEFAULT ''

ALTER TABLE [MovTrn01]
DROP CONSTRAINT MovtrnAntMovTrn01_DEFAULT