USE ProntoOut
GO 

DECLARE @LIMITE INT;
DECLARE @I INT;

SET @I = 1;
SELECT @LIMITE = MAX(ESTCOD) FROM EST;

WHILE @I <= @LIMITE
BEGIN
	EXEC RELTEMPAUDITORIA @I, '025ADM', '', '';
	SET @I = @I + 1;
	PRINT @I;
END