CREATE TABLE [LOG_VLRPAG] ( 
  [Log_VlrPagId]                  DECIMAL(18)    NOT NULL    IDENTITY ( 1 , 1 ), 
  [Log_VlpNumLan]                 DECIMAL(18)    NULL, 
  [Log_VlpNumLanOri]              DECIMAL(18)    NULL, 
  [Log_VlpNumLanCan]              DECIMAL(18)    NULL, 
  [Log_VlpDtaVct]                 DATETIME    NULL, 
  [Log_VlpDtaOriVct]              DATETIME    NULL, 
  [Log_VlpVlrPag]                 MONEY    NULL, 
  [Log_VlpVlrOriPag]              MONEY    NULL, 
  [Log_VlpVlrTaxAdm]              MONEY    NULL, 
  [Log_VlpPerVlrAluPos]           SMALLMONEY    NULL, 
  [Log_VlpVlrEfeito]              MONEY    NULL, 
  [Log_VlpNumMovPrv]              INT    NULL, 
  [Log_VlpNumRegPrv]              INT    NULL, 
  [Log_VlpNumRegLiq]              INT    NULL, 
  [Log_VlpNumMovCan]              INT    NULL, 
  [Log_VlpNumRegCan]              INT    NULL, 
  [Log_VlpDtaEnvBco]              DATETIME    NULL, 
  [Log_VlpMovTrnId]               DECIMAL(18)    NULL, 
  [Log_VlpBan]                    SMALLINT    NOT NULL, 
  [Log_VlpTipPrd]                 CHAR(1)    NULL, 
  [Log_VlpDtaLiq]                 DATETIME    NULL, 
  [Log_VlpVlrPagLiq]              MONEY    NULL, 
  [Log_VlpArbNum]                 INT    NULL, 
  [Log_VlpArbLotNum]              SMALLINT    NULL, 
  [Log_VlpArbDetSeq]              INT    NULL, 
  [Log_VlrPag_EstCod]             INT    NULL, 
  [Log_VlpStspag]                 SMALLINT    NULL, 
  [Log_TidCod]                    SMALLINT    NULL, 
  [Log_VlpVlrCstTrnPln]           MONEY    NULL, 
  [Log_VlpVlrCstTrnEst]           MONEY    NULL, 
  [Log_VlpVlrTaxFinBF]            MONEY    NULL, 
  [Log_VlpVlrTarCreBF]            MONEY    NULL, 
  [Log_VlpNumTotPar]              SMALLINT    NULL, 
  [Log_VlpUsuInc]                 VARCHAR(128)    NULL, 
  [Log_VlpDtiInc]                 DATETIME    NULL, 
  [Log_VlpUsuAlt]                 VARCHAR(128)    NULL, 
  [Log_VlpDtiAlt]                 DATETIME    NULL, 
  [Log_VlpMesRefAlu]              SMALLINT    NULL, 
  [Log_VlpIndExpCtb]              VARCHAR(1)    NULL, 
  [Log_VlpDtaExpCtb]              DATETIME    NULL, 
  [Log_VlpAnpTip]                 CHAR(1)    NULL, 
  [Log_VlpAnpNum]                 DECIMAL(18)    NULL, 
  [Log_VlpVlrParBru]              MONEY    NULL, 
  [Log_VlpUng2Cod]                INT    NULL, 
  [Log_VlpBnfTip]                 CHAR(1)    NULL, 
  [Log_VlpBnfCod]                 DECIMAL(18)    NULL, 
  [Log_VlpTrnCod]                 CHAR(2)    NULL, 
  [Log_VlpNumPar]                 SMALLINT    NULL, 
  [Log_VlpNsu]                    DECIMAL(12)    NULL, 
  [Log_VlpAutCodStr]              VARCHAR(12)    NULL, 
  [Log_VlpEnvTrn]                 DATETIME    NULL, 
  [Log_VlpIdTransation]           DECIMAL(18)    NULL, 
  [Log_VlpVanWbsSeq]              INT    NULL, 
  [Log_VlpIdCreditTransaction]    DECIMAL(18)    NULL, 
  [Log_VlpIdCreditTransactionPai] DECIMAL(18)    NULL, 
  [Log_VlrPagRegRec]              BIT    NULL, 
  [Log_VlpAltTrn]                 DATETIME    NULL, 
  [Log_VlpCreditoCessao]          SMALLINT    NULL, 
  [Log_VlrPagEnvJson]             VARCHAR(MAX)    NULL, 
  [Log_VlrPagRetJson]             VARCHAR(MAX)    NULL, 
  [Log_VlrMesComp]                VARCHAR(7)    NULL, 
  [Log_VlrIdExt]                  VARCHAR(8)    NULL, 
  [Log_VlrUsuAlt]                 VARCHAR(128)    NULL, 
  [Log_VlpDtaAlt]                 DATETIME    NULL, 
     PRIMARY KEY ( [Log_VlrPagId] ))

	 SELECT distinct(VlpBnfTip) FROM VLRPAG