/*RODAR APENAS PARA CLIENTE PRONTO*/
USE [Pronto]
GO

/****** Object:  StoredProcedure [dbo].[InsereRelTempAuditoria]    Script Date: 12/09/2022 17:07:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE Procedure [dbo].[InsereRelTempAuditoria]( @ESTCOD as integer, @UsrId as Varchar(20) )
As
Begin

INSERT INTO RELTEMPVENDA
SELECT A.MovTrnId,
A.EstCod,
A.MovTrnDta,
A.MovTrnNsu,
A.MovTrnAutCodStr,
A.MovTrnCod,
A.MovTrnBan,
A.MovTrnTipPrd,
A.MovTrnVlr,
A.MovTrnVlrLiqEst,
B.BANCO_DETALHE,
F.VALOR_CESSAO,
D.CUSTO_ANTECIPACAO,
E.VALOR_CANCELADO,
C.VALOR_ABERTO,
@UsrId,
GetDate()
FROM MOVTRN01 A
LEFT JOIN (
SELECT VLPMOVTRNID,
SUM(VLPVLRPAG) BANCO_DETALHE
FROM VLRPAG
WHERE ESTCOD = @ESTCOD
AND VlpArbNum > 0
AND VlpStspag = 2--LIQUIDADO
GROUP BY VlpMovTrnId) B
ON A.MovTrnId = B.VlpMovTrnId
LEFT JOIN (
SELECT VLPMOVTRNID,
SUM(VLPVLRPAG) VALOR_ABERTO
FROM VLRPAG
WHERE ESTCOD = @ESTCOD
AND VlpStspag = 1--ABERTO
GROUP BY VlpMovTrnId) C
ON A.MovTrnId = C.VlpMovTrnId
LEFT JOIN (
SELECT A.VlpMovTrnId,
SUM(B.LaaVlrTxaAnt) CUSTO_ANTECIPACAO
FROM VLRPAG A
INNER JOIN LANANT B
ON A.VlpNumLan = B.LaaNumLan
WHERE ESTCOD = @ESTCOD
AND VlpAnpNum > 0
GROUP BY VlpMovTrnId) D
ON A.MovTrnId = D.VlpMovTrnId
LEFT JOIN (
SELECT VLPMOVTRNID,
SUM(VLPVLRPAG) VALOR_CANCELADO
FROM VLRPAG
WHERE ESTCOD = @ESTCOD
AND VlpStspag = 3--CANCELADO
GROUP BY VlpMovTrnId) E
ON A.MovTrnId = E.VlpMovTrnId
LEFT JOIN (
SELECT A.VlpMovTrnId,
SUM(B.CessaoDetValor) VALOR_CESSAO
FROM VLRPAG A
INNER JOIN CESSAODETALHE B
ON A.VlpNumLan = B.CessaoDetNumLan
WHERE ESTCOD = @ESTCOD
GROUP BY VlpMovTrnId) F
ON A.MovTrnId = F.VlpMovTrnId
WHERE ESTCOD = @ESTCOD
UNION ALL
SELECT
A.VlpMovTrnId,
A.EstCod,
MovTrnDta,
MovTrnNsu,
MovTrnAutCodStr,
MovTrnCod,
MovTrnBan,
'Cessão' PRODUTO,
MovTrnVlr,
VlpVlrPag, 
IIF(VlpStspag = 2, VLPVLRPAG, 0) BANCO_DETALHE, 
IIF(VlpIdCreditTransaction > 0 AND VLPSTSPAG = 6, VlpVlrPag, 0) VALOR_CESSAO,
IIF(VLPANPNUM > 0, (SELECT LaaVlrTxaAnt FROM LANANT WHERE LAANUMLAN = A.VLPNUMLAN), 0) ANTECIPADO,
IIF(VlpStspag = 3, VLPVLRPAG, 0) CANCELADO,
IIF(VlpStspag = 1, VlpVlrPag, 0) VALOR_ABERTO,
@UsrId,
GetDate()
FROM VLRPAG A
LEFT JOIN MovTrn01 B
ON A.VlpMovTrnId = B.MovTrnId
WHERE A.EstCod = @ESTCOD
AND A.VlpIdCreditTransactionPai IN 
(SELECT CessaoId FROM CESSAO 
WHERE CessaoEstCodBen = @ESTCOD
AND CessaoStatusId = 1);

END
GO


