
USE [Pronto]
GO

delete from [dbo].[PARSIS] where [ParCod] = 'PARCELAS_MENOR_QUE_HOJE'

INSERT INTO [dbo].[PARSIS] ([ParCod], [ParDsc], [ParTipPar], [ParTamPar], [ParIndSin], [ParCon], [ParDtiInc], [ParFlgInt])
					VALUES ('IMPORTAREDECAPTURADO', 'Transação do Dia', 'CA', '3','N' ,'S', '2022-05-12', '0')
GO

USE [Banese]
GO

delete from [dbo].[PARSIS] where [ParCod] = 'PARCELAS_MENOR_QUE_HOJE'

INSERT INTO [dbo].[PARSIS] ([ParCod], [ParDsc], [ParTipPar], [ParTamPar], [ParIndSin], [ParCon], [ParDtiInc], [ParFlgInt])
					VALUES ('IMPORTAREDECAPTURADO', 'Transação do Dia', 'CA', '3','N' ,'S', '2022-05-12', '0')
GO

USE [BemFacil]
GO

delete from [dbo].[PARSIS] where [ParCod] = 'PARCELAS_MENOR_QUE_HOJE'

INSERT INTO [dbo].[PARSIS] ([ParCod], [ParDsc], [ParTipPar], [ParTamPar], [ParIndSin], [ParCon], [ParDtiInc], [ParFlgInt])
					VALUES ('IMPORTAREDECAPTURADO', 'Transação do Dia', 'CA', '3','N' ,'S', '2022-05-12', '0')
GO

USE [Credinov]
GO

delete from [dbo].[PARSIS] where [ParCod] = 'PARCELAS_MENOR_QUE_HOJE'

INSERT INTO [dbo].[PARSIS] ([ParCod], [ParDsc], [ParTipPar], [ParTamPar], [ParIndSin], [ParCon], [ParDtiInc], [ParFlgInt])
					VALUES ('IMPORTAREDECAPTURADO', 'Transação do Dia', 'CA', '3','N' ,'S', '2022-05-12', '0')
GO

USE [CredPag]
GO

delete from [dbo].[PARSIS] where [ParCod] = 'PARCELAS_MENOR_QUE_HOJE'

INSERT INTO [dbo].[PARSIS] ([ParCod], [ParDsc], [ParTipPar], [ParTamPar], [ParIndSin], [ParCon], [ParDtiInc], [ParFlgInt])
					VALUES ('IMPORTAREDECAPTURADO', 'Transação do Dia', 'CA', '3','N' ,'S', '2022-05-12', '0')
GO

USE [SmartPagamentos]
GO

delete from [dbo].[PARSIS] where [ParCod] = 'PARCELAS_MENOR_QUE_HOJE'

INSERT INTO [dbo].[PARSIS] ([ParCod], [ParDsc], [ParTipPar], [ParTamPar], [ParIndSin], [ParCon], [ParDtiInc], [ParFlgInt])
					VALUES ('IMPORTAREDECAPTURADO', 'Transação do Dia', 'CA', '3','N' ,'S', '2022-05-12', '0')
GO


  
  
  