USE SMARTPAGAMENTOS
GO
/*RODAR APENAS PARA SMARTPAGAMENTOS*/
INSERT INTO PARSIS (ParCod, ParCon, ParTipPar, ParTamPar)
VALUES (
'SMART_SKIP_MOVIMENTO', 'S', 'CA', 1
),(
'SMART_SKIP_VALOR', '20000', 'CA', 20
),(
'NOVA_CAPTURA', 'S', 'CA', 1
)