
USE [Pronto]
GO
ALTER TABLE [ADQ0008] 
ADD [AdqMccGrupoSegmento] CHAR(150)    NOT NULL CONSTRAINT AdqMccGrupoSegmentoADQ0008_DEFAULT DEFAULT ''
GO

USE [Banese]
GO
ALTER TABLE [ADQ0008] 
ADD [AdqMccGrupoSegmento] CHAR(150)    NOT NULL CONSTRAINT AdqMccGrupoSegmentoADQ0008_DEFAULT DEFAULT ''
GO

USE [BemFacil]
GO
ALTER TABLE [ADQ0008] 
ADD [AdqMccGrupoSegmento] CHAR(150)    NOT NULL CONSTRAINT AdqMccGrupoSegmentoADQ0008_DEFAULT DEFAULT ''
GO

USE [Credinov]
GO
ALTER TABLE [ADQ0008] 
ADD [AdqMccGrupoSegmento] CHAR(150)    NOT NULL CONSTRAINT AdqMccGrupoSegmentoADQ0008_DEFAULT DEFAULT ''
GO

USE [CredPag]
GO
ALTER TABLE [ADQ0008] 
ADD [AdqMccGrupoSegmento] CHAR(150)    NOT NULL CONSTRAINT AdqMccGrupoSegmentoADQ0008_DEFAULT DEFAULT ''
GO

USE [SmartPagamentos]
GO
ALTER TABLE [ADQ0008] 
ADD [AdqMccGrupoSegmento] CHAR(150)    NOT NULL CONSTRAINT AdqMccGrupoSegmentoADQ0008_DEFAULT DEFAULT ''
GO


  
  
  